package com.visualthreat.testing.core.tests;

public class VehicleConstant {

	public static final String[] VEHICLE_MANUFACTURER = { 
			"--请选择车厂--", "Jeep", "MINI", "奥迪", "宝骏", "宝马", "宝沃", "北汽", 
			"奔驰", "奔腾", "本田", "比亚迪", "标致", "别克", "大众", "东风", 
			"东南", "菲亚特", "丰田", "福特", "福田", 
			"观致", "广汽传祺", "广汽吉奥", "广汽三菱", "哈弗", "海马", "红旗", 
			"华泰", "吉利汽车", "江淮", "江铃", "捷豹", "凯迪拉克", "克莱斯勒", "雷克萨斯", "雷诺", "猎豹汽车", 
			"林肯", "铃木", "领克", "陆风", "路虎", "路特斯", "马自达", "名爵", "讴歌", "奇瑞", 
			"启辰", "起亚", "日产", "荣威", "上汽大通", "斯巴鲁", "斯柯达", "特斯拉", "蔚来", 
			"沃尔沃", "五菱汽车", "现代", "雪佛兰", "雪铁龙", "一汽", "依维柯", "英菲尼迪", "云度", "长安", 
			"长城", "知豆", "众泰",  };
	
	public static final String[] VEHICLE_MANUFACTURER_ENG = { 
			"--Please choose the car factory--", "Jeep", "MINI", "Audi", "Baojun", "BMW", "Baowo", "Beiqi",
			"Benz", "Pentium", "Honda", "BYD", "Peugeot", "Buick", "Popular", "Dongfeng",
			"Southeast", "Fiat", "Toyota", "Ford", "Futian",
			"Guanzhi", "Guangzhou Chuanqi", "Guangzhou Automobile", "Guangzhou Mitsubishi", "Haver", "Hai Ma", "Red Flag",
			"Huatai", "Geely Car", "Jianghuai", "Jiangling", "Jaguar", "Cadillac", "Chrysler", "Lexus", "Renault", "Cheetah Car",
			"Lincoln", "Suzuki", "Linke", "Landwind", "Land Rover", "Lutus", "Mazda", "Mage", "Yangge", "Chery",
			"Qi Chen", "Kia", "Nissan", "Roewe", "SAIC Chase", "Subaru", "Skoda", "Tesla", "Wei Lai",
			"Volvo", "Wuling Car", "Modern", "Chevrolet", "Citroen", "FAW", "Iveco", "Infiniti", "Cloud", "Changan",
			"Great Wall", "Knowledge Bean", "Zhongtai",  };

	public static final String[][] VEHICLE_MODEL = { 
			{"--请选择车型--", }, 
			{"Jeep(进口) 大切诺基(进口)", "Jeep(进口) 指南者(进口)", "Jeep(进口) 牧马人", "Jeep(进口) 自由光(进口)", "Jeep(进口) 自由客", 
				"广汽菲克Jeep 大指挥官", "广汽菲克Jeep 指南者", "广汽菲克Jeep 指挥官", "广汽菲克Jeep 自由侠", "广汽菲克Jeep 自由光", }, 
			{"MINI", }, 
			{"一汽-大众奥迪 奥迪A3", "一汽-大众奥迪 奥迪A4L", "一汽-大众奥迪 奥迪A6", "一汽-大众奥迪 奥迪A6L", "一汽-大众奥迪 奥迪A6L新能源", 
				"一汽-大众奥迪 奥迪Q3", "一汽-大众奥迪 奥迪Q5", "一汽-大众奥迪 奥迪Q5L", "奥迪(进口) 奥迪A1", "奥迪(进口) 奥迪A3(进口)", 
				"奥迪(进口) 奥迪A3新能源(进口)", "奥迪(进口) 奥迪A4(进口)", "奥迪(进口) 奥迪A5", "奥迪(进口) 奥迪A6(进口)", "奥迪(进口) 奥迪A7", 
				"奥迪(进口) 奥迪A8", "奥迪(进口) 奥迪Q3(进口)", "奥迪(进口) 奥迪Q7", "奥迪(进口) 奥迪Q7新能源", "奥迪(进口) 奥迪S3", 
				"奥迪(进口) 奥迪S4", "奥迪(进口) 奥迪S5", "奥迪(进口) 奥迪S6", "奥迪(进口) 奥迪S7", "奥迪(进口) 奥迪S8", 
				"奥迪(进口) 奥迪SQ5", "奥迪(进口) 奥迪TT", "奥迪(进口) 奥迪TTS", }, 
			{"上汽通用五菱 宝骏310", }, 
			{"华晨宝马 宝马1系", "华晨宝马 宝马2系旅行车", "华晨宝马 宝马3系", "华晨宝马 宝马5系", "华晨宝马 宝马5系新能源", 
				"华晨宝马 宝马X1", "华晨宝马 宝马X1新能源", "华晨宝马 宝马X3", "宝马(进口) 宝马1系(进口)", "宝马(进口) 宝马2系", 
				"宝马(进口) 宝马2系多功能旅行车", "宝马(进口) 宝马2系旅行车(进口)", "宝马(进口) 宝马3系(进口)", "宝马(进口) 宝马3系GT", "宝马(进口) 宝马4系", 
				"宝马(进口) 宝马5系(进口)", "宝马(进口) 宝马5系GT", "宝马(进口) 宝马6系", "宝马(进口) 宝马6系GT", "宝马(进口) 宝马7系", 
				"宝马(进口) 宝马7系新能源", "宝马(进口) 宝马i3", "宝马(进口) 宝马i8", "宝马(进口) 宝马X2", "宝马(进口) 宝马X3(进口)", 
				"宝马(进口) 宝马X4", "宝马(进口) 宝马X5", "宝马(进口) 宝马X5新能源", "宝马(进口) 宝马X6", }, 
			{"宝沃汽车 宝沃BX5", "宝沃汽车 宝沃BX6", "宝沃汽车 宝沃BX7", "宝沃汽车 宝沃BXi7", }, 
			{"北汽瑞丽 道达V8", "北汽银翔 北汽幻速H2", "北京汽车 绅宝CC", "北京汽车 北汽威旺306", "LITE", "北汽新能源 EC系列", "北汽新能源 EH系列", "北汽新能源 EU系列", "北汽新能源 EV系列", 
				"北汽新能源 EX系列", "北汽新能源 北汽新能源ES210", "北京汽车制造厂 勇士", "北京汽车制造厂 北京BW007", "北京汽车制造厂 战旗", }, 
			{"北京奔驰 奔驰C级", "北京奔驰 奔驰C级新能源", "北京奔驰 奔驰E级", "北京奔驰 奔驰GLA", "北京奔驰 奔驰GLC", 
				"北京奔驰 奔驰GLK级", "奔驰(进口) 奔驰A级(进口)", "奔驰(进口) 奔驰B级", "奔驰(进口) 奔驰CLA级", "奔驰(进口) 奔驰CLS级", 
				"奔驰(进口) 奔驰C级(进口)", "奔驰(进口) 奔驰E级(进口)", "奔驰(进口) 奔驰GLA(进口)", "奔驰(进口) 奔驰GLC(进口)", "奔驰(进口) 奔驰GLE", 
				"奔驰(进口) 奔驰GLE新能源", "奔驰(进口) 奔驰GLS", "奔驰(进口) 奔驰GL级", "奔驰(进口) 奔驰G级", "奔驰(进口) 奔驰M级", 
				"奔驰(进口) 奔驰R级", "奔驰(进口) 奔驰SLC级", "奔驰(进口) 奔驰SLK级", "奔驰(进口) 奔驰SL级", "奔驰(进口) 奔驰S级", 
				"奔驰(进口) 奔驰S级新能源", }, 
			{"一汽奔腾 奔腾B30", }, 
			{"东风本田 哥瑞", "东风本田 思域", "东风本田 思铂睿", "东风本田 本田CR-V", "东风本田 本田UR-V", 
				"东风本田 本田XR-V", "东风本田 杰德", "东风本田 竞瑞", "东风本田 艾力绅", "广汽本田 冠道", 
				"广汽本田 凌派", "广汽本田 奥德赛", "广汽本田 歌诗图", "广汽本田 缤智", "广汽本田 锋范", 
				"广汽本田 雅阁", "广汽本田 飞度", }, 
			{"比亚迪 元", "比亚迪 元新能源", "比亚迪 唐", "比亚迪 唐新能源", "比亚迪 宋", 
				"比亚迪 宋MAX", "比亚迪 宋新能源", "比亚迪 比亚迪e5", "比亚迪 比亚迪e6", "比亚迪 比亚迪F0", 
				"比亚迪 比亚迪F3", "比亚迪 比亚迪L3", "比亚迪 比亚迪M6", "比亚迪 比亚迪S7", "比亚迪 秦", 
				"比亚迪 速锐", }, 
			{"东风标致 标致2008", }, 
			{"上汽通用别克 VELITE 5", "上汽通用别克 凯越", "上汽通用别克 别克GL6", "上汽通用别克 君威", "上汽通用别克 君越", 
				"上汽通用别克 威朗", "上汽通用别克 昂科威", "上汽通用别克 昂科拉", "上汽通用别克 英朗", "上汽通用别克 阅朗", 
				"其他 别克新世纪", }, 
			{"一汽-大众 C-TREK蔚领", "一汽-大众 T-ROC探歌", "一汽-大众 一汽-大众CC", "一汽-大众 宝来", "一汽-大众 捷达", 
				"一汽-大众 迈腾", "一汽-大众 速腾", "一汽-大众 高尔夫", "一汽-大众 高尔夫·嘉旅", "上汽大众 Polo", 
				"上汽大众 凌渡", "上汽大众 帕萨特", "上汽大众 朗境", "上汽大众 朗行", "上汽大众 朗逸", 
				"上汽大众 桑塔纳", "上汽大众 桑塔纳经典", "上汽大众 辉昂", "上汽大众 途安", "上汽大众 途昂", 
				"上汽大众 途观", "上汽大众 途观L", "大众(进口) Tiguan", "大众(进口) 凯路威", "大众(进口) 夏朗", 
				"大众(进口) 大众e-up", "大众(进口) 大众up", "大众(进口) 尚酷", "大众(进口) 甲壳虫", "大众(进口) 蔚揽", 
				"大众(进口) 辉腾", "大众(进口) 迈特威", "大众(进口) 迈腾(进口)", "大众(进口) 途锐", "大众(进口) 高尔夫(进口)", 
				"大众(进口) 高尔夫新能源(进口)", }, 
			{"东风汽车 东风皮卡", "东风汽车 御风", "郑州日产 帅客", "郑州日产 帅客新能源", "郑州日产 锐骐皮卡", "郑州日产 东风风度MX5", 
				"东风风光", "东风风行 景逸", "东风风行 菱智", "东风风行 风行CM7", "东风乘用车 东风A9", "东风乘用车 东风风神", "东风小康 ", }, 
			{"东南汽车 V3菱悦", "东南汽车 V5菱致", "东南汽车 V6菱仕", "东南汽车 东南DX3", "东南汽车 东南DX3新能源", 
				"东南汽车 东南DX7", }, 
			{"广汽菲克菲亚特 致悦", "广汽菲克菲亚特 菲翔", }, 
			{"一汽丰田 RAV4荣放", "一汽丰田 兰德酷路泽", "一汽丰田 卡罗拉", "一汽丰田 奕泽IZOA", "一汽丰田 威驰", 
				"一汽丰田 威驰FS", "一汽丰田 普拉多", "一汽丰田 柯斯达", "一汽丰田 皇冠", "丰田(进口) Fortuner", 
				"丰田(进口) Sienna", "丰田(进口) 丰田86", "丰田(进口) 兰德酷路泽(进口)", "丰田(进口) 埃尔法", "广汽丰田 YARiS L 致享", 
				"广汽丰田 丰田C-HR", "广汽丰田 凯美瑞", "广汽丰田 汉兰达", "广汽丰田 逸致", "广汽丰田 雷凌", }, 
			{"江铃福特 全顺", "江铃福特 撼路者", "江铃福特 新世代全顺", "江铃福特 经典全顺", "江铃福特 途睿欧", 
				"福特(进口) Mustang", "福特(进口) Ranger", "福特(进口) 探险者", "福特(进口) 福克斯(进口)", "福特(进口) 福特F-150", 
				"长安福特 福克斯", "长安福特 福睿斯", "长安福特 翼搏", "长安福特 翼虎", "长安福特 蒙迪欧", 
				"长安福特 蒙迪欧新能源", "长安福特 金牛座", "长安福特 锐界", }, 
			{"福田汽车 图雅诺", "福田汽车 图雅诺EV", "福田汽车 祥菱M", "福田汽车 祥菱V", "福田汽车 福田风景", 
				"福田汽车 萨普", "福田汽车 蒙派克E", "福田汽车 风景G7", "福田汽车 伽途GT", "福田汽车 拓陆者", "福田汽车 萨瓦纳", }, 
			{"观致汽车 观致3", "观致汽车 观致5", }, 
			{"广汽乘用车 传祺GA3S视界", "广汽乘用车 传祺GA4", "广汽乘用车 传祺GA5新能源", "广汽乘用车 传祺GA6", "广汽乘用车 传祺GA8", 
				"广汽乘用车 传祺GM8", "广汽乘用车 传祺GS3", "广汽乘用车 传祺GS4", "广汽乘用车 传祺GS5 Super", "广汽乘用车 传祺GS7", 
				"广汽乘用车 传祺GS8", "广汽新能源 传祺GA3S PHEV", "广汽新能源 传祺GE3", "广汽新能源 传祺GS4新能源", }, 
			{"广汽吉奥 广汽吉奥GP150", }, 
			{"广汽三菱 祺智PHEV", "劲炫ASX", "欧蓝德", "三菱(进口) 帕杰罗(进口)", "三菱(进口) 欧蓝德(进口)", }, 
			{"长城汽车 哈弗H1", "长城汽车 哈弗H2", "长城汽车 哈弗H2s", "长城汽车 哈弗H4", "长城汽车 哈弗H5", 
				"长城汽车 哈弗H6", "长城汽车 哈弗H7", "长城汽车 哈弗H8", "长城汽车 哈弗H9", "长城汽车 哈弗M6", }, 
			{"一汽海马 丘比特", "一汽海马 普力马EV", "一汽海马 海马M8", "海马汽车 海马S5青春版", "海马汽车 海马爱尚EV", }, 
			{"一汽红旗 新明仕", "一汽红旗 红旗H5", "一汽红旗 红旗H7", "其他 红旗", }, 
			{"华泰汽车 圣达菲", "华泰汽车 圣达菲经典", "华泰汽车 宝利格", "华泰汽车 路盛E80", }, 
			{"吉利汽车 博瑞", "吉利汽车 博瑞GE", "吉利汽车 博瑞GE新能源", "吉利汽车 博越", "吉利汽车 吉利EC8", 
				"吉利汽车 吉利GX7", "吉利汽车 帝豪", "吉利汽车 帝豪新能源", "吉利汽车 海景", "吉利汽车 熊猫", 
				"吉利汽车 自由舰", "吉利汽车 英伦C5", "吉利汽车 豪情SUV", "吉利汽车 远景", "吉利汽车 金刚", 
				"吉利汽车 金刚财富", }, 
			{"江淮汽车 和悦", "江淮汽车 和悦A30", "江淮汽车 帅铃T6", "江淮汽车 征途", "江淮汽车 星锐", 
				"江淮汽车 江淮iEV", "江淮汽车 江淮iEV6E", "江淮汽车 江淮iEV6S", "江淮汽车 江淮iEV7S", "江淮汽车 江淮iEVA50", 
				"江淮汽车 江淮V7", "江淮汽车 瑞铃", "江淮汽车 瑞风", "江淮汽车 瑞风A60", "江淮汽车 瑞风M3", 
				"江淮汽车 瑞风M4", "江淮汽车 瑞风M5", "江淮汽车 瑞风M6", "江淮汽车 瑞风R3", "江淮汽车 瑞风S2", 
				"江淮汽车 瑞风S2mini", "江淮汽车 瑞风S3", "江淮汽车 瑞风S5", "江淮汽车 瑞风S7", }, 
			{"江铃汽车 域虎", "江铃汽车 宝典", "江铃汽车 特顺", }, 
			{"奇瑞捷豹路虎 捷豹XEL", "奇瑞捷豹路虎 捷豹XFL", "捷豹 捷豹F-PACE", }, 
			{"上汽通用凯迪拉克 凯迪拉克", "凯迪拉克(进口) 凯雷德ESCALADE", }, 
			{"克莱斯勒(进口) 克莱斯勒300C(进口)", "克莱斯勒(进口) 大捷龙(进口)", }, 
			{"雷克萨斯 雷克萨斯CT", }, 
			{"东风雷诺 科雷傲", "东风雷诺 科雷嘉", "雷诺(进口) Espace", "雷诺(进口) 卡缤", "雷诺(进口) 科雷傲(进口)", 
				"雷诺(进口) 纬度", "雷诺(进口) 风朗", }, 
			{"猎豹汽车 Mattu", "猎豹汽车 猎豹C5EV", }, 
			{"林肯 林肯MKC", "林肯 林肯MKX", "林肯 林肯MKZ", "林肯 林肯大陆", "林肯 领航员", }, 
			{"昌河铃木 利亚纳A6", "昌河铃木 北斗星", "昌河铃木 北斗星X5", "铃木(进口) 吉姆尼(进口)", "铃木(进口) 英格尼斯", 
				"长安铃木 启悦", }, 
			{"领克 领克01", "领克 领克01新能源", "领克 领克02", }, 
			{"陆风汽车 陆风X2", }, 
			{"奇瑞捷豹路虎 发现神行", "奇瑞捷豹路虎 揽胜极光", "路虎(进口) 卫士", "路虎(进口) 发现", "路虎(进口) 发现神行(进口)", 
				"路虎(进口) 揽胜", "路虎(进口) 揽胜新能源", "路虎(进口) 揽胜星脉", "路虎(进口) 揽胜极光(进口)", "路虎(进口) 揽胜运动版", 
				"路虎(进口) 揽胜运动版新能源", "路虎(进口) 神行者2", }, 
			{"路特斯 Elise", "路特斯 Evora", "路特斯 Exige", }, 
			{"一汽马自达 睿翼", "一汽马自达 阿特兹", "一汽马自达 马自达6", "一汽马自达 马自达8", "一汽马自达 马自达CX-4", 
				"长安马自达 马自达3 Axela昂克赛拉", "长安马自达 马自达3星骋", "长安马自达 马自达CX-5", "马自达(进口) 马自达CX-3", "马自达(进口) 马自达MX-5", }, 
			{"上汽集团 名爵3", "上汽集团 锐腾", "上汽集团 锐行", }, 
			{"广汽讴歌 讴歌CDX", "广汽讴歌 讴歌TLX-L", "讴歌(进口) 讴歌MDX", "讴歌(进口) 讴歌NSX", "讴歌(进口) 讴歌RDX(进口)", 
				"讴歌(进口) 讴歌RLX", "讴歌(进口) 讴歌TLX", }, 
			{"奇瑞新能源 奇瑞eQ", "奇瑞新能源 奇瑞eQ1", "奇瑞新能源 瑞虎3xe", "奇瑞新能源 艾瑞泽5e", "奇瑞汽车 奇瑞E3", 
				"奇瑞汽车 瑞虎3", "奇瑞汽车 瑞虎3x", "奇瑞汽车 瑞虎5", "奇瑞汽车 瑞虎5x", "奇瑞汽车 瑞虎7", 
				"奇瑞汽车 瑞虎8", "奇瑞汽车 艾瑞泽3", "奇瑞汽车 艾瑞泽5", "奇瑞汽车 艾瑞泽7", "奇瑞汽车 艾瑞泽7e", 
				"奇瑞汽车 艾瑞泽M7", "奇瑞汽车 风云2", }, 
			{"东风启辰 启辰D50", "东风启辰 晨风", }, 
			{"东风悦达起亚 KX CROSS", "东风悦达起亚 凯绅", "东风悦达起亚 智跑", "东风悦达起亚 焕驰", "东风悦达起亚 福瑞迪", 
				"东风悦达起亚 起亚K2", "起亚(进口) 嘉华(进口)", "起亚(进口) 斯汀格", "起亚(进口) 极睿", "起亚(进口) 索兰托", 
				"起亚(进口) 起亚K9", "起亚(进口) 霸锐", }, 
			{"东风日产 LANNIA 蓝鸟", "东风日产 劲客", "东风日产 天籁", "东风日产 奇骏", "东风日产 楼兰", 
				"东风日产 玛驰", "东风日产 西玛", "东风日产 轩逸", "东风日产 逍客", "东风日产 阳光", 
				"东风日产 骊威", "东风日产 骐达", "日产(进口) 日产370Z", "日产(进口) 日产GT-R", "日产(进口) 贵士", 
				"日产(进口) 途乐", "郑州日产 日产NV200", "郑州日产 纳瓦拉", "郑州日产 途达", }, 
			{"上汽集团 荣威350", "上汽集团 荣威360", "上汽集团 荣威950", "上汽集团 荣威e50", "上汽集团 荣威e550", 
				"上汽集团 荣威e950", "上汽集团 荣威Ei5", "上汽集团 荣威ei6", "上汽集团 荣威i6", "上汽集团 荣威RX3", 
				"上汽集团 荣威RX5", "上汽集团 荣威RX5新能源", "上汽集团 荣威RX8", }, 
			{"上汽大通 上汽大通", }, 
			{"斯巴鲁 傲虎", "斯巴鲁 力狮", "斯巴鲁 斯巴鲁BRZ", "斯巴鲁 斯巴鲁XV", "斯巴鲁 森林人", }, 
			{"上汽斯柯达 Yeti", "上汽斯柯达 明锐", "上汽斯柯达 昕动", "上汽斯柯达 昕锐", "上汽斯柯达 晶锐", 
				"上汽斯柯达 柯珞克", "上汽斯柯达 柯米克", "上汽斯柯达 柯迪亚克", "上汽斯柯达 速派", "斯柯达(进口) 明锐(进口)", }, 
			{"特斯拉 Model S", "特斯拉 Model X", }, 
			{"蔚来 蔚来ES8", }, 
			{"沃尔沃(进口) 沃尔沃S60", "沃尔沃(进口) 沃尔沃S90(进口)", "沃尔沃(进口) 沃尔沃V40", "沃尔沃(进口) 沃尔沃V60", "沃尔沃(进口) 沃尔沃V90", 
				"沃尔沃(进口) 沃尔沃XC40", "沃尔沃(进口) 沃尔沃XC60(进口)", "沃尔沃(进口) 沃尔沃XC90", "沃尔沃(进口) 沃尔沃XC90新能源", "沃尔沃亚太 沃尔沃S60L", 
				"沃尔沃亚太 沃尔沃S60L新能源", "沃尔沃亚太 沃尔沃S90", "沃尔沃亚太 沃尔沃S90新能源", "沃尔沃亚太 沃尔沃XC60", "沃尔沃亚太 沃尔沃XC60新能源", 
				"长安沃尔沃 沃尔沃S80L", }, 
			{"上汽通用五菱 五菱之光", "上汽通用五菱 五菱宏光", "上汽通用五菱 五菱征程", "上汽通用五菱 五菱荣光", }, 
			{"北京现代 伊兰特EV", "北京现代 全新胜达", "北京现代 北京现代ix25", "北京现代 北京现代ix35", "北京现代 名图", 
				"北京现代 悦动", "北京现代 悦纳", "北京现代 悦纳RV", "北京现代 朗动", "北京现代 瑞奕", 
				"北京现代 瑞纳", "北京现代 索纳塔九", "北京现代 索纳塔八", "北京现代 索纳塔新能源", "北京现代 途胜", 
				"北京现代 领动", "现代(进口) Veloster飞思", "现代(进口) 捷恩斯", "现代(进口) 格越", "现代(进口) 雅尊", }, 
			{"上汽通用雪佛兰 乐风RV", "上汽通用雪佛兰 创酷", "上汽通用雪佛兰 探界者", "上汽通用雪佛兰 科帕奇", "上汽通用雪佛兰 科沃兹", 
				"上汽通用雪佛兰 科鲁兹", "上汽通用雪佛兰 赛欧", "上汽通用雪佛兰 迈锐宝", "上汽通用雪佛兰 迈锐宝XL", "雪佛兰(进口) 库罗德", 
				"雪佛兰(进口) 科迈罗", "雪佛兰(进口) 索罗德", }, 
			{"长安标致雪铁龙", "东风雪铁龙 C4世嘉", "东风雪铁龙 世嘉", "东风雪铁龙 天逸 C5 AIRCROSS", "东风雪铁龙 爱丽舍", 
				"东风雪铁龙 雪铁龙C3-XR", "东风雪铁龙 雪铁龙C4L", "东风雪铁龙 雪铁龙C5", "东风雪铁龙 雪铁龙C6", "雪铁龙(进口) C4 PICASSO", }, 
			{"一汽吉林 佳宝", "天津一汽 夏利N7", }, 
			{"南京依维柯 依维柯Daily(欧胜)", }, 
			{"东风英菲尼迪 英菲尼迪Q50L", "东风英菲尼迪 英菲尼迪QX50", "英菲尼迪(进口) 英菲尼迪Q50", }, 
			{"云度新能源 云度", }, 
			{"长安汽车 凌轩", "长安汽车 奔奔", "长安汽车 奔奔EV", "长安汽车 悦翔V3", "长安汽车 悦翔V7", 
				"长安汽车 睿骋", "长安汽车 睿骋CC", "长安汽车 逸动", "长安汽车 逸动DT", "长安汽车 逸动新能源", 
				"长安汽车 长安CS15", "长安汽车 长安CS15EV", "长安汽车 长安CS35", "长安汽车 长安CS55", "长安汽车 长安CS75", 
				"长安汽车 长安CS95", "长安跨越 新豹MINI", "长安跨越 跨越王", "长安跨越 长安V3", 
				"长安汽车 奔奔mini-e", "长安汽车 欧力威", "长安汽车 欧力威EV", "长安汽车 欧尚", "长安汽车 欧尚A800", 
				"长安汽车 欧尚X70A", "长安汽车 欧诺", "长安汽车 长安CX70", "长安汽车 长安之星3", "长安汽车 长安之星9", 
				"长安汽车 长安星卡", }, 
			{"长城汽车 WEY P8", "长城汽车 WEY VV5", "长城汽车 WEY VV7", "长城汽车 长城C30", "长城汽车 长城C30新能源", 
				"长城汽车 长城C50", "长城汽车 长城M4", "长城汽车 风骏5", "长城汽车 风骏6", }, 
			{"知豆电动车 知豆D1", }, 
			{"众泰汽车 云100", "众泰汽车 众泰E200", "众泰汽车 大迈X5", "众泰汽车 江南T11", "众泰汽车 芝麻", }, 
		};
	
	public static final String[][] VEHICLE_MODEL_ENG = {
			{"--Please select the model--", },
			{"Jeep (import) Grand Cherokee (import)", "Jeep (import) guide (import)", "Jeep (import) Wrangler", "Jeep (import) free light (import)", "Jeep (import) free Guest",
			"Guangzhou Fick Jeep Commander", "Guangzhou Fick Jeep Guide", "Guangzhou Fick Jeep Commander", "Guangzhou Fick Jeep Freeman", "Guangzhou Fick Jeep Free Light", },
			{"MINI", },
			{"FAW-Volkswagen Audi Audi A3", "FAW-VW Audi Audi A4L", "FAW-VW Audi Audi A6", "FAW-VW Audi Audi A6L", "FAW-VW Audi Audi A6L New Energy",
			"FAW-Volkswagen Audi Audi Q3", "FAW-VW Audi Audi Q5", "FAW-VW Audi Audi Q5L", "Audi (import) Audi A1", "Audi (import) Audi A3 (import)",
			"Audi (import) Audi A3 new energy (import)", "Audi (import) Audi A4 (import)", "Audi (import) Audi A5", "Audi (import) Audi A6 (import)", "Audi ( Import) Audi A7",
			"Audi (import) Audi A8", "Audi (import) Audi Q3 (import)", "Audi (import) Audi Q7", "Audi (import) Audi Q7 new energy", "Audi (import) Audi S3",
			"Audi (import) Audi S4", "Audi (import) Audi S5", "Audi (import) Audi S6", "Audi (import) Audi S7", "Audi (import) Audi S8",
			"Audi (import) Audi SQ5", "Audi (import) Audi TT", "Audi (import) Audi TTS", },
			{"SAIC General Wuling Baojun 310", },
			{"Brilliance BMW BMW 1 Series", "Brilliance BMW BMW 2 Series Touring Car", "Brilliance BMW BMW 3 Series", "Brilliance BMW BMW 5 Series", "Brilliance BMW BMW 5 Series New Energy",
			"Brilliance BMW BMW X1", "Brilliance BMW BMW X1 New Energy", "Brilliance BMW BMW X3", "BMW (Import) BMW 1 Series (Import)", "BMW (Import) BMW 2 Series",
			"BMW (import) BMW 2 Series multi-purpose wagon", "BMW (import) BMW 2 Series wagon (import)", "BMW (import) BMW 3 Series (import)", "BMW (import) BMW 3 Series GT", "BMW (import) BMW 4 Series",
			"BMW (Import) BMW 5 Series (Import)", "BMW (Import) BMW 5 Series GT", "BMW (Import) BMW 6 Series", "BMW (Import) BMW 6 Series GT", "BMW (Import) BMW 7 Series",
			"BMW (Import) BMW 7 Series New Energy", "BMW (Import) BMW i3", "BMW (Import) BMW i8", "BMW (Import) BMW X2", "BMW (Import) BMW X3 (Import)" ,
			"BMW (import) BMW X4", "BMW (import) BMW X5", "BMW (import) BMW X5 New Energy", "BMW (import) BMW X6", },
			{"Baowo car Baowo BX5", "Baowo car Baowo BX6", "Baowo car Baowo BX7", "Baowo car Baowo BXi7", },
			{"Beiqi Ruili Daoda V8", "Beiqi Yinxiang Beiqi Magic Speed ​​H2", "Beijing Auto Baobao CC", "Beijing Auto Beiqi Weiwang 306", "LITE", "Beiqi New Energy EC Series", "Beiqi New Energy EH Series", "Beiqi New Energy EU Series", "Beiqi New Energy EV Series",
			"Beiqi New Energy EX Series", "Beiqi New Energy Beiqi New Energy ES210", "Beijing Automobile Manufacturing Factory Warrior", "Beijing Automobile Manufacturing Plant Beijing BW007", "Beijing Automobile Manufacturing Factory Battle Flag", },
			{"Beijing Benz Mercedes-Benz C-Class", "Beijing Benz Mercedes-Benz C-Class New Energy", "Beijing Benz Mercedes-Benz E-Class", "Beijing Benz Mercedes-Benz GLA", "Beijing Benz Mercedes-Benz GLC",
			"Beijing Mercedes-Benz Mercedes-Benz GLK class", "Benz (import) Mercedes-Benz A-class (import)", "Benz (import) Mercedes-Benz B-class", "Benz (import) Mercedes-Benz CLA-class", "Benz (import) Mercedes-Benz CLS-class" ,
			"Benz (import) Mercedes-Benz C-class (import)", "Benz (import) Mercedes-Benz E-class (import)", "Benz (import) Mercedes-Benz GLA (import)", "Benz (import) Mercedes-Benz GLC (import)", "Benz (import) Mercedes-Benz GLE",
			"Benz (import) Mercedes-Benz GLE new energy", "Benz (import) Mercedes-Benz GLS", "Benz (import) Mercedes-Benz GL-class", "Benz (import) Mercedes-Benz G-class", "Benz (import) Mercedes-Benz M-class",
			"Benz (import) Mercedes-Benz R-class", "Benz (import) Mercedes-Benz SLC-class", "Benz (import) Mercedes-Benz SLK-class", "Benz (import) Mercedes-Benz SL-class", "Benz (import) Mercedes-Benz S-class",
			"Benz (import) Mercedes-Benz S-class new energy", },
			{"FAW Pentium Pentium B30", },
			{"Dongfeng Honda Gore", "Dongfeng Honda Civic", "Dongfeng Honda Platinum Core", "Dongfeng Honda Honda CR-V", "Dongfeng Honda Honda UR-V",
			"Dongfeng Honda Honda XR-V", "Dongfeng Honda Jade", "Dongfeng Honda Jingrui", "Dongfeng Honda Eric", "Guangzhou Honda Crown Road",
			"Guangzhou Honda Lingpai", "Guangzhou Honda Odyssey", "Guangzhou Honda Song Poetry", "Guangzhou Honda Binzhi", "Guangzhou Honda Fengfan",
			"Guangzhou Honda Accord", "Guangzhou Honda Fit", },
			{"BYD Yuan", "BYD Yuan New Energy", "BYD Tang", "BYD Tang New Energy", "BYD Song",
			"BYD Song MAX", "BYD Song New Energy", "BYD BYD e5", "BYD BYD e6", "BYD BYD F0",
			"BYD BYD F3", "BYD BYD L3", "BYD BYD M6", "BYD BYD S7", "BYD Qin",
			"BYD Speedy", },
			{"Dongfeng Peugeot Peugeot 2008", },
			{"SAIC GM Buick VELITE 5", "SAIC GM Buick Excelle", "SAIC GM Buick GL6", "SAIC GM Buick Regal", "SAIC GM Buick LaCrosse",
			"SAIC GM Buick Weilang", "SAIC GM Buick Angkewei", "SAIC GM Buick Angola", "SAIC GM Buick Yinglang", "SAIC GM Buick Lang",
			"Other Buick New Century", },
			{"FAW-Volkswagen C-TREK Wei Ling", "FAW-Volkswagen T-ROC Detecting Song", "FAW-Volkswagen FAW-Volkswagen CC", "FAW-Volkswagen Bora", "FAW-Volkswagen Jetta",
			"FAW-Volkswagen Magotan", "FAW-Volkswagen Sagitar", "FAW-Volkswagen Golf", "FAW-Volkswagen Golf·Jialv", "SAIC Volkswagen Polo",
			"SAIC Volkswagen Lingdu", "SAIC Volkswagen Passat", "SAIC Volkswagen Langjing", "SAIC Volkswagen Langxing", "SAIC Volkswagen Langyi",
			"SAIC Volkswagen Santana", "SAIC Volkswagen Santana Classic", "SAIC Volkswagen Hui Ang", "SAIC Volkswagen Touran", "SAIC Volkswagen Wayang",
			"SAIC Volkswagen Tiguan", "SAIC Volkswagen Tiguan L", "Volkswagen (Import) Tiguan", "Volkswagen (Import) Kailuwei", "Volkswagen (Import) Sharan",
			"Volkswagen (import) Volkswagen e-up", "Volkswagen (import) Volkswagen up", "Volkswagen (import) Scirocco", "Volkswagen (import) beetle", "Volkswagen (import))",
			"Volkswagen (import) Phaeton", "Volkswagen (import) Maitewei", "Volkswagen (import) Magotan (import)", "Volkswagen (import) Touareg", "Volkswagen (import) golf (import)",
			"Volkswagen (import) golf new energy (import)", },
			{"Dongfeng Motor Dongfeng Pickup", "Dongfeng Motor Yufeng", "Zhengzhou Nissan Shuai Ke", "Zhengzhou Nissan Shuai Ke New Energy", "Zhengzhou Nissan Ruiqi Pickup", "Zhengzhou Nissan Dongfeng Style MX5",
			"Dongfeng scenery", "Dongfeng Fengxing Jingyi", "Dongfeng Fengxing Lingzhi", "Dongfeng popular CM7", "Dongfeng passenger car Dongfeng A9", "Dongfeng passenger car Dongfeng Fengshen", "Dongfeng Xiaokang", },
			{"Southeast Auto V3 Ling Yue", "Southeast Auto V5 Lingzhi", "Southeast Auto V6 Lingshi", "Southeast Auto Southeast DX3", "Southeast Auto Southeast DX3 New Energy",
			"Southeast Auto Southeast DX7", },
			{"Guangzhou Fick Fiat", "Guangzhou Fick Fiat Philippine", },
			{"FAW Toyota RAV4 Rongfang", "FAW Toyota Land Cruiser", "FAW Toyota Corolla", "FAW Toyota Zeozawa IZOA", "FAW Toyota Vios",
			"FAW Toyota Vios FS", "FAW Toyota Prado", "FAW Toyota Kosta", "FAW Toyota Crown", "Toyota (Import) Fortuner",
			"Toyota (Import) Sienna", "Toyota (Import) Toyota 86", "Toyota (Import) Land Cruiser (Import)", "Toyota (Import) Elfa", "Guangzhou Toyota YARiS L" ,
			"Guangzhou Toyota Toyota C-HR", "Guangzhou Toyota Camry", "Guangzhou Toyota Highlander", "Guangzhou Toyota Yizhi", "Guangzhou Toyota Rayling", },
			{"Jiangling Ford Transit", "Jiangling Ford Roadr", "Jiangling Ford New Generation Transit", "Jiangling Ford Classic Transit", "Jiangling Ford Touruiou",
			"Ford (Import) Mustang", "Ford (Import) Ranger", "Ford (Import) Explorer", "Ford (Import) Fox (Import)", "Ford (Import) Ford F-150",
			"Changan Ford Focus", "Changan Ford Fu Ruisi", "Changan Ford Wings", "Changan Ford Wing Tiger", "Changan Ford Mondeo",
			"Changan Ford Mondeo New Energy", "Changan Ford Taurus", "Changan Ford Sharp", },
			{"Futian Auto Tuyanuo", "Futian Auto Tuanya EV", "Futian Auto Xiangling M", "Futian Auto Xiangling V", "Futian Auto Futian Landscape",
			"Futian Auto Sapu", "Futian Auto Montacip E", "Futian Auto Landscape G7", "Futian Auto Gaitu GT", "Futian Auto Tudor", "Futian Auto Savanna", },
			{"Guanzhi Auto Guanzhi 3", "Guanzhi Auto Guanzhi 5", },
			{"Guangzhou Passenger Car Chuanqi GA3S Vision", "Guangzhou Automobile Passenger Car Chuanqi GA4", "Guangzhou Automobile Passenger Car Chuanqi GA5 New Energy", "Guangzhou Automobile Passenger Car Chuanqi GA6", "Guangzhou Passenger Car Pass祺GA8",
			"Guangzhou Automobile Passenger Car Chuanqi GM8", "Guangzhou Automobile Passenger Car Chuanqi GS3", "Guangzhou Automobile Passenger Car Chuanqi GS4", "Guangzhou Automobile Passenger Car Chuanqi GS5 Super", "Guangzhou Automobile Passenger Car Chuanqi GS7" ,
			"Guangzhou Automobile Passenger Car Chuanqi GS8", "Guangzhou New Energy Chuanqi GA3S PHEV", "Guangzhou New Energy Chuanqi GE3", "Guangzhou New Energy Chuanqi GS4 New Energy", },
			{"Guangzhou Gio Guangzhou Automobile Gio GP150", },
			{"Guangzhou Mitsubishi 祺智PHEV", "Jingxuan ASX", "Outlander", "Mitsubishi (import) Pajero (import)", "Mitsubishi (import) Outlander (import)", },
			{"Great Wall Car Haval H1", "Great Wall Car Haval H2", "Great Wall Car Haval H2s", "Great Wall Car Haval H4", "Great Wall Car Haval H5",
			"Great Wall Car Haval H6", "Great Wall Car Haval H7", "Great Wall Car Haval H8", "Great Wall Car Haval H9", "Great Wall Car Haval M6", },
			{"FAW Hippocampus Cupid", "FAW Haima Premarin EV", "FAW Haima Haima M8", "Hai Ma Auto Haima S5 Youth Edition", "Hai Ma Auto Haima Ai Shang EV", },
			{"FAC Red Flag New Mingshi", "FAW Red Flag Red Flag H5", "FAW Red Flag Red Flag H7", "Other Red Flag", },
			{"Huatai Automobile Santa Fe", "Huatai Automobile Santa Fe Classic", "Huatai Automobile Baolig", "Huatai Automobile Road Sheng E80", },
			{"Geely Cars Borui", "Geely Cars Borui GE", "Geely Cars Borui GE New Energy", "Geely Cars Bo Yue", "Geely Cars Geely EC8",
			"Geely Car Geely GX7", "Geely Car Emgrand", "Geely Car Emgrand New Energy", "Geely Car Seascape", "Geely Car Panda",
			"Geely Car Free Ship", "Geely Car British C5", "Geely Car Luxury SUV", "Geely Car Vision", "Geely Car King Kong",
			"Geely Automobile King Kong Fortune", },
			{"Jianghuai Automobile and Yue", "Jianghuai Automobile and Yue A30", "Jianghuai Automobile Shuailing T6", "Jianghuai Automobile Journey", "Jianghuai Automobile Star Rui",
			"Jianghuai Automobile Jianghuai iEV", "Jianghuai Automobile Jianghuai iEV6E", "Jianghuai Automobile Jianghuai iEV6S", "Jianghuai Automobile Jianghuai iEV7S", "Jianghuai Automobile Jianghuai iEVA50",
			"Jianghuai Automobile Jianghuai V7", "Jianghuai Automobile Ruiling", "Jianghuai Automobile Ruifeng", "Jianghuai Automobile Ruifeng A60", "Jianghuai Automobile Ruifeng M3",
			"Jianghuai Automobile Ruifeng M4", "Jianghuai Automobile Ruifeng M5", "Jianghuai Automobile Ruifeng M6", "Jianghuai Automobile Ruifeng R3", "Jianghuai Automobile Ruifeng S2",
			"Jianghuai Automobile Ruifeng S2mini", "Jianghuai Automobile Ruifeng S3", "Jianghuai Automobile Ruifeng S5", "Jianghuai Automobile Ruifeng S7", },
			{"Jiangling Motors Domain Tiger", "Jiangling Motors Collection", "Jiangling Motors Special", },
			{"Chery Jaguar Land Rover Jaguar XEL", "Chery Jaguar Land Rover Jaguar XFL", "Jaguar Jaguar F-PACE", },
			{"SAIC General Cadillac Cadillac", "Cadillac (Import) Escalade ESCALADE", },
			{"Chrysler (Import) Chrysler 300C (Import)", "Chrysler (Import) Grand Jet (Import)", },
			{"Lexus Lexus CT", },
			{"Dongfeng Renault Koleo", "Dongfeng Renault Correga", "Renault (import) Espace", "Renault (import) Kabun", "Renault (import) Koleos (import)",
			"Renault (import) latitude", "Renault (import) wind lang", },
			{"Cheetah Car Mattu", "Cheetah Car Cheetah C5EV", },
			{"Lincoln Lincoln MKC", "Lincoln Lincoln MKX", "Lincoln Lincoln MKZ", "Lincoln Lincoln Continental", "Lincoln Navigator", },
			{"Changhe Suzuki Liana A6", "Changhe Suzuki Big Dipper", "Changhe Suzuki Big Dipper X5", "Suzuki (Import) Jimny (Import)", "Suzuki (Import) Ingnis",
			"Changan Suzuki Kai Yue", },
			{"Lunk gram 01", "Lectra Lingke 01 New Energy", "Lectra Lingke 02", },
			{"Landwind Car Landwind X2", },
			{"Chery Jaguar Land Rover Discovery of God", "Chery Jaguar Land Rover Range Rover Aurora", "Land Rover (Import) Guardian", "Land Rover (Import) Discovery", "Land Rover (Import) Discover God (Import)",
			"Land Rover (Import) Range Rover", "Land Rover (Import) Range Rover New Energy", "Land Rover (Import) Range Rover Star", "Land Rover (Import) Range Rover Aurora (Import)", "Land Rover (Import) Range Rover Sport Edition",
			"Land Rover (Import) Range Rover Sport Edition New Energy", "Land Rover (Import) Freelander 2", },
			{"Routes Elise", "Lutters Evora", "Lutters Exige", },
			{"FAW Mazda Ruiyi", "FAW Mazda Artez", "FAW Mazda Mazda 6", "FAR Mazda Mazda 8", "Faw Mazda Mazda CX-4",
			"Chang'an Mazda Mazda 3 Axela Angkeira", "Chang'an Mazda Mazda 3 Stars", "Chang'an Mazda Mazda CX-5", "Mazda (Import) Mazda CX-3", "Mazda (Import) Mazda MX-5 ", },
			{"SAIC Group MG 3", "SAIC Group Rui Teng", "SAIC Group Ruixing", },
			{"Guangzhou Yangge Acura CDX", "Guangzhou Carol Yangko TLX-L", "Yangge (Import) Acura MDX", "Yangge (Import) Acura NSX", "Yangge (Import) Acura RDX (Import)",
			"Yangge (Import) Acura RLX", "Yangge (Import) Acura TLX", },
			{"Chery New Energy Chery eQ", "Chery New Energy Chery eQ1", "Chery New Energy Tiggo 3xe", "Chery New Energy Arrizo 5e", "Chery Car Chery E3",
			"Chery Auto Tiggo 3", "Chery Auto Tiggo 3x", "Chery Auto Tiggo 5", "Chery Auto Tiggo 5x", "Chery Auto Tiggo 7",
			"Chery Cars Tiggo 8", "Chery Cars Arrizo 3", "Chery Cars Arrizo 5", "Chery Cars Arrizo 7", "Chery Cars Arrizo 7e",
			"Chery Auto Arrizo M7", "Chery Car Fengyun 2", },
			{"Dongfeng Qichen Kaichen D50", "Dongfeng Qichen Morning Wind", },
			{"Dongfeng Yueda Kia KX CROSS", "Dongfeng Yueda Kia Kay", "Dongfeng Yueda Kia Zhirun", "Dongfeng Yueda Kia Huan Chi", "Dongfeng Yueda Kia Furuidi",
			"Dongfeng Yueda Kia Kia K2", "Kia (import) Ka Wah (import)", "Kia (import) Stinger", "Kia (import)", "Kia (import) Sorento",
			"Kia (import) Kia K9", "Kia (import) Pa Rui", },
			{"Dongfeng Nissan LANNIA Bluebird", "Dongfeng Nissan Jinke", "Dongfeng Nissan Tianzhu", "Dongfeng Nissan Qijun", "Dongfeng Nissan Loulan",
			"Dongfeng Nissan Ma Chi", "Dongfeng Nissan Sima", "Dongfeng Nissan Sylphy", "Dongfeng Nissan Hacker", "Dongfeng Nissan Sunshine",
			"Dongfeng Nissan Converse", "Dongfeng Nissan Tiida", "Nissan (import) Nissan 370Z", "Nissan (import) Nissan GT-R", "Nissan (import) nobles",
			"Nissan (import) Tule", "Zhengzhou Nissan Nissan NV200", "Zhengzhou Nissan Navarre", "Zhengzhou Nissan Tuda", },
			{"SAIC Group Roewe 350", "SAIC Group Roewe 360", "SAIC Group Roewe 950", "SAIC Group Roewe e50", "SAIC Group Roewe e550",
			"SAIC Group Roewe e950", "SAIC Group Roewe Ei5", "SAIC Group Roewe ei6", "SAIC Group Roewe i6", "SAIC Group Roewe RX3",
			"SAIC Group Roewe RX5", "SAIC Group Roewe RX5 New Energy", "SAIC Group Roewe RX8", },
			{"SAIC Chase SAIC Chase", },
			{"Subaru Outback", "Sbaru Legacy", "Subaru Subaru BRZ", "Sbaru Subaru XV", "Subaru Forester", },
			{"Shangqi Skoda Yeti", "Shangqi Skoda Octavia", "Shangqi Skoda Instigation", "Shangqi Skoda Hao Rui", "Shangqi Skoda Jing Rui",
			"Shangqi Skoda Ke Keke", "Shangda Skoda Komik", "Shangqi Skoda Kodiak", "Shangda Skoda Speed", "Skoda (Import) Mingrui (Import)", },
			{"Tesla Model S", "Tesla Model X", },
			{"Weilai Weilai ES8", },
			{"Volvo (import) Volvo S60", "Volvo (import) Volvo S90 (import)", "Volvo (import) Volvo V40", "Volvo (import) Volvo V60", "Volvo (import) Volvo V90",
			"Volvo (import) Volvo XC40", "Volvo (import) Volvo XC60 (import)", "Volvo (import) Volvo XC90", "Volvo (import) Volvo XC90 new energy", "Volvo Asia Pacific Volvo S60L",
			"Volvo Asia Pacific Volvo S60L New Energy", "Volvo Asia Pacific Volvo S90", "Volvo Asia Pacific Volvo S90 New Energy", "Volvo Asia Pacific Volvo XC60", "Volvo Asia Pacific Volvo XC60 New Energy",
			"Changan Volvo Volvo S80L", },
			{"Shangqi General Wuling Wuling Light", "SAIC General Wuling Wuling Hongguang", "SAIC General Wuling Wuling Journey", "SAIC General Wuling Wuling Rongguang", },
			{"Beijing Hyundai Elantra EV", "Beijing Hyundai New Shengda", "Beijing Hyundai Beijing Hyundai ix25", "Beijing Hyundai Beijing Hyundai ix35", "Beijing Modern Famous Map",
			"Beijing Hyundai Elantra", "Beijing Hyundai Acceptance", "Beijing Hyundai Acceptance RV", "Beijing Hyundai Lang", "Beijing Hyundai Ruiqi",
			"Beijing Hyundai Rena", "Beijing Hyundai Sonata Nine", "Beijing Hyundai Sonata Eight", "Beijing Hyundai Sonata New Energy", "Beijing Hyundai Tucson",
			"Beijing Modern Leadership", "Modern (imported) Veloster", "Modern (imported) Jens", "Modern (Imported) Ge Yue", "Modern (Imported) Yazun", },
			{"SAIC GM Chevrolet Lova RV", "SAIC GM Chevrolet Chuang Cool", "SAIC General Chevrolet Detector", "SAIC GM Chevrolet Copaci", "SAIC GM Chevrolet Kovaz",
			"SAIC GM Chevrolet Cruze", "SAIC GM Chevrolet Sail", "SAIC GM Chevrolet Mai Rui Bao", "SAIC GM Chevrolet Mai Rui Bao XL", "Chevrolet (import) Kurod",
			"Chevrolet (import) Comalo", "Chevrolet (import) Sorod", },
			{"Chang'an Peugeot Citroen", "Dongfeng Citroen C4 Sega", "Dongfeng Citroen Sega", "Dongfeng Citroen Tianyi C5 AIRCROSS", "Dongfeng Citroen Elysee",
			"Dongfeng Citroen Citroen C3-XR", "Dongfeng Citroen Citroen C4L", "Dongfeng Citroen Citroen C5", "Dongfeng Citroen Citroen C6", "Citroen (Import) C4 PICASSO", },
			{"FAW Jilin Jiabao", "Tianjin FAW Xiali N7", },
			{"Nanjing Iveco Iveco Daily", },
			{"Dongfeng Infiniti Infiniti Q50L", "Dongfeng Infiniti Infiniti QX50", "Infiniti (Import) Infiniti Q50", },
			{"Cloudy new energy cloud", },
			{"Changan Automobile Lingxuan", "Changan Automobile Benben", "Changan Automobile Benben EV", "Changan Automobile Yuexiang V3", "Changan Automobile Yuexiang V7",
			"Changan Automobile Ruihao", "Changan Automobile Ruiqi CC", "Changan Automobile Yidong", "Changan Automobile Yidong DT", "Changan Automobile Yidong New Energy",
			"Changan Automobile Changan CS15", "Changan Automobile Changan CS15EV", "Changan Automobile Changan CS35", "Changan Automobile Changan CS55", "Changan Automobile Changan CS75",
			"Changan Automobile Changan CS95", "Changan Crossing New Leopard MINI", "Changan Crossing the King", "Changan Crossing Changan V3",
			"Changan Auto Bennimini-e", "Changan Auto Ouliwei", "Changan Auto Ouliwei EV", "Changan Auto Auchan", "Changan Auto Auchan A800",
			"Changan Automobile Auchan X70A", "Changan Automobile Ou Nuo", "Changan Automobile Changan CX70", "Changan Automobile Changan Star 3", "Changan Automobile Changan Star 9",
			"Changan Automobile Changan Star Card", },
			{"Great Wall Motor WEY P8", "Great Wall Motor WEY VV5", "Great Wall Motor WEY VV7", "Great Wall Motor Great Wall C30", "Great Wall Motor Great Wall C30 New Energy",
			"Great Wall Motor Great Wall C50", "Great Wall Motor Great Wall M4", "Great Wall Motor Feng Jun 5", "Great Wall Motor Feng Jun 6", },
			{"Zhidou electric car Zhidou D1", },
			{"Zhongtai Auto Cloud 100", "Zhongtai Auto Zhongtai E200", "Zhongtai Auto Damai X5", "Zhongtai Auto Jiangnan T11", "Zhongtai Auto Sesame", },
	};

	public static final String[] VEHICLE_YEAR = { 
			"--请选择年份--", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010",
			"2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995"};
	public static final String[] VEHICLE_YEAR_ENG = {
			"--Please select the year --", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010",
			"2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995" };

	public static final String CAN_PINOUT = "总线引脚";
	public static final String CAN_PINOUT_ENG = "BUS Pin";

	public static final String[] ARRAY_CAN_PINOUT = { 
			"--请选择总线引脚--", "6-14", "3-11", "1-9", "其他", };
	public static final String[] ARRAY_CAN_PINOUT_ENG = {
			"--Please select the BUS pin--", "6-14", "3-11", "1-9", "其他", };

	public static final String BAUD_RATES = "波特率";
	public static final String BAUD_RATES_ENG = "Baud Rate";

	public static final String[] ARRAY_BAUD_RATES =
	    {"--请选择波特率--", "5k", "10k", "20k", "25k", "40k", "50k", "75k", "100k", "125k", "200k", "250k", "400k", "500k", "600k", "750k", "1000k"};
	public static final String[] ARRAY_BAUD_RATES_ENG =
			{"--Please select the baud rate--", "5k", "10k", "20k", "25k", "40k", "50k", "75k", "100k", "125k", "200k", "250k", "400k", "500k", "600k", "750k", "1000k"};

	public static final String ROAD_CONDITION = "路况";
	public static final String ROAD_CONDITION_ENG = "Road Condition";

	public static final String[] ARRAY_ROAD_CONDITION = { 
			"--请选择路况--", "高速", "本地", "怠速", "关机", };
	public static final String[] ARRAY_ROAD_CONDITION_ENG =
			{"--Please select the road conditions--", "High speed", "Local", "Idle speed", "Shutdown", };

	public static final String[] ARRAY_TIME = { 
		"--请选择时间--", "20", "120", "300", "2000", "3600", };
	public static final String[] ARRAY_TIME_ENG = {
			"--Please select time--", "20", "120", "300", "2000", "3600", };
	
	public static final String[] ARRAY_BYTE_ENG = {
			"0", "1", "2", "3", "4", "5", "6", "7", };

}


