/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_visualthreat_util_VTMerge */

#ifndef _Included_com_visualthreat_util_VTMerge
#define _Included_com_visualthreat_util_VTMerge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_visualthreat_util_VTMerge
 * Method:    initLog
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_visualthreat_util_VTMerge_initLog
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_visualthreat_util_VTMerge
 * Method:    initLzma
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_visualthreat_util_VTMerge_initLzma
  (JNIEnv *, jobject);

/*
 * Class:     com_visualthreat_util_VTMerge
 * Method:    initBz2
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_visualthreat_util_VTMerge_initBz2
  (JNIEnv *, jobject);

/*
 * Class:     com_visualthreat_util_VTMerge
 * Method:    setTmpDirpath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_visualthreat_util_VTMerge_setTmpDirpath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_visualthreat_util_VTMerge
 * Method:    flushLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_visualthreat_util_VTMerge_flushLog
  (JNIEnv *, jobject);

/*
 * Class:     com_visualthreat_util_VTMerge
 * Method:    merge01
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_visualthreat_util_VTMerge_merge01
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_visualthreat_util_VTMerge
 * Method:    merge02
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_visualthreat_util_VTMerge_merge02
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_visualthreat_util_VTMerge
 * Method:    merge
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_visualthreat_util_VTMerge_merge
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
